global using CryptoArbitrage.Domain.Models;
global using CryptoArbitrage.Application.Interfaces;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Configuration;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks; 