name: Backend Tests

on:
  pull_request:
    paths:
      - 'backend/**'
  push:
    branches: 
      - main
      - develop
    paths:
      - 'backend/**'
  workflow_dispatch:  # Allows manual triggering

jobs:
  test-backend:
    name: Run Backend Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      
      - name: Install dependencies
        run: dotnet restore backend/CryptoArbitrage.sln
      
      - name: Build
        run: dotnet build backend/CryptoArbitrage.sln --configuration Release
      
      - name: Run all tests
        run: dotnet test backend/CryptoArbitrage.sln --configuration Release --verbosity normal --no-restore
      
      - name: Generate test coverage
        run: |
          dotnet tool install --global dotnet-reportgenerator-globaltool
          dotnet test backend/CryptoArbitrage.sln --collect:"XPlat Code Coverage" --results-directory ./coverage
          reportgenerator -reports:./coverage/**/coverage.cobertura.xml -targetdir:./coverage/report -reporttypes:HtmlInline_AzurePipelines
      
      - name: Upload test coverage results
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-report
          path: ./coverage/report
          retention-days: 7 